### ISSUE TITLE
Short outputcache API controller

### ISSUE THREAD

**Issue by apjones6** [TruffleMuffin/Decisions#35]
As all the information is in the URL, it would be very easy to output cache the results for, say, 5 seconds. Just to deal with any repeated requests resulting from high load.

Could be a configurable outputcache too, if not applied through the attribute. Might be best, so you can tailor the caching strategy for the usage.

**Comment by TruffleMuffin** [comment]
Please see https://github.com/TruffleMuffin/Decisions/blob/develop/Decisions/Services/Cache/DecisionService.cs for an already configurable Caching implementation for Decisions, it defaults to 5seconds.

OutputCache attributes are not implemented within the Http namespace for ApiController. As I understand it this was a by design choice by the Mvc team as they felt that it was not something that should be happening on an Api endpoint, and if it was there were better strategies for dealing with it. For example a reverse Http Proxy.

Im not saying great minds think alike. But errr. Evidence to the contrary is dwindling?
